Connected web3 provider at 10.195.2.37:8001
Date.now(): 1580881413220 startTime: 1580881509793 delay: 96576
Deploying smart contract from 0x232ee988523d3f8d7c18c2ae3c3b73e11e80cd0f
TX HASH:
 0x794f6f13f6028a551657aa31666e87199d34dcad8664c86d4e830aee4e63b792
RECEIPT:
 {
  blockHash: '0x5e242ca2a9ad6bb311e0b9b283f68987e557635e0a4227cbca83cf523a85cbe6',
  blockNumber: 6,
  contractAddress: '0x476b19Bb83c5DE9C2f09052b1C659304178C1E64',
  cumulativeGasUsed: 436990,
  from: '0x232ee988523d3f8d7c18c2ae3c3b73e11e80cd0f',
  gasUsed: 218495,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  status: true,
  to: null,
  transactionHash: '0x794f6f13f6028a551657aa31666e87199d34dcad8664c86d4e830aee4e63b792',
  transactionIndex: 1
}
Contract at: 0x476b19Bb83c5DE9C2f09052b1C659304178C1E64

Evaluating  7500txs...

Sending TXS started at 1580881509880 ...
startingBlock: 13
... Sending TXS finished at 1580881612193
Total send duration: 102313
... Waiting for mining process to finish! ...
(node:12320) UnhandledPromiseRejectionWarning: Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/home/ubuntu/benchprezz/node_modules/web3-core-method/node_modules/web3-utils/src/index.js:56:17)
    at /home/ubuntu/benchprezz/node_modules/web3-core-method/src/index.js:260:23
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
(node:12320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERROR:
 Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/home/ubuntu/benchprezz/node_modules/web3-core-method/node_modules/web3-utils/src/index.js:56:17)
    at /home/ubuntu/benchprezz/node_modules/web3-core-method/src/index.js:260:23
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
========================================================
========================================================

/home/ubuntu/benchprezz/benchmark/tpsUnsigned.js:113
                throw 'Blockchain capabilities EXCEEDED - ABORTING test run!';
                ^
Blockchain capabilities EXCEEDED - ABORTING test run!
